// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package client

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
// const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRequest struct {
	Document             []byte   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *CreateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *CreateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ReadRequest struct {
	Find                 []byte       `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string       `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Options              *ReadOptions `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	Meta                 *Meta        `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *ReadRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *ReadRequest) GetOptions() *ReadOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *ReadRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ReadOptions struct {
	Select               map[string]int32 `protobuf:"bytes,1,rep,name=select,proto3" json:"select,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Sort                 map[string]int32 `protobuf:"bytes,2,rep,name=sort,proto3" json:"sort,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Skip                 int64            `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	Limit                int64            `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Distinct             string           `protobuf:"bytes,5,opt,name=distinct,proto3" json:"distinct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReadOptions) Reset()         { *m = ReadOptions{} }
func (m *ReadOptions) String() string { return proto.CompactTextString(m) }
func (*ReadOptions) ProtoMessage()    {}
func (*ReadOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ReadOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOptions.Unmarshal(m, b)
}
func (m *ReadOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOptions.Marshal(b, m, deterministic)
}
func (m *ReadOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOptions.Merge(m, src)
}
func (m *ReadOptions) XXX_Size() int {
	return xxx_messageInfo_ReadOptions.Size(m)
}
func (m *ReadOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOptions.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOptions proto.InternalMessageInfo

func (m *ReadOptions) GetSelect() map[string]int32 {
	if m != nil {
		return m.Select
	}
	return nil
}

func (m *ReadOptions) GetSort() map[string]int32 {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *ReadOptions) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ReadOptions) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadOptions) GetDistinct() string {
	if m != nil {
		return m.Distinct
	}
	return ""
}

type UpdateRequest struct {
	Find                 []byte   `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Update               []byte   `protobuf:"bytes,3,opt,name=update,proto3" json:"update,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *UpdateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *UpdateRequest) GetUpdate() []byte {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *UpdateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type DeleteRequest struct {
	Find                 []byte   `protobuf:"bytes,1,opt,name=find,proto3" json:"find,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *DeleteRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *DeleteRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type AggregateRequest struct {
	Pipeline             []byte   `protobuf:"bytes,1,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Operation            string   `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Meta                 *Meta    `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregateRequest) Reset()         { *m = AggregateRequest{} }
func (m *AggregateRequest) String() string { return proto.CompactTextString(m) }
func (*AggregateRequest) ProtoMessage()    {}
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *AggregateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregateRequest.Unmarshal(m, b)
}
func (m *AggregateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregateRequest.Marshal(b, m, deterministic)
}
func (m *AggregateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregateRequest.Merge(m, src)
}
func (m *AggregateRequest) XXX_Size() int {
	return xxx_messageInfo_AggregateRequest.Size(m)
}
func (m *AggregateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AggregateRequest proto.InternalMessageInfo

func (m *AggregateRequest) GetPipeline() []byte {
	if m != nil {
		return m.Pipeline
	}
	return nil
}

func (m *AggregateRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *AggregateRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Response struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Result               []byte   `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

type Meta struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	DbType               string   `protobuf:"bytes,2,opt,name=dbType,proto3" json:"dbType,omitempty"`
	Col                  string   `protobuf:"bytes,3,opt,name=col,proto3" json:"col,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *Meta) GetDbType() string {
	if m != nil {
		return m.DbType
	}
	return ""
}

func (m *Meta) GetCol() string {
	if m != nil {
		return m.Col
	}
	return ""
}

func (m *Meta) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AllRequest struct {
	Col                  string   `protobuf:"bytes,1,opt,name=col,proto3" json:"col,omitempty"`
	Document             []byte   `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	Operation            string   `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Find                 []byte   `protobuf:"bytes,4,opt,name=find,proto3" json:"find,omitempty"`
	Update               []byte   `protobuf:"bytes,5,opt,name=update,proto3" json:"update,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllRequest) Reset()         { *m = AllRequest{} }
func (m *AllRequest) String() string { return proto.CompactTextString(m) }
func (*AllRequest) ProtoMessage()    {}
func (*AllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *AllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllRequest.Unmarshal(m, b)
}
func (m *AllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllRequest.Marshal(b, m, deterministic)
}
func (m *AllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllRequest.Merge(m, src)
}
func (m *AllRequest) XXX_Size() int {
	return xxx_messageInfo_AllRequest.Size(m)
}
func (m *AllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllRequest proto.InternalMessageInfo

func (m *AllRequest) GetCol() string {
	if m != nil {
		return m.Col
	}
	return ""
}

func (m *AllRequest) GetDocument() []byte {
	if m != nil {
		return m.Document
	}
	return nil
}

func (m *AllRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

func (m *AllRequest) GetFind() []byte {
	if m != nil {
		return m.Find
	}
	return nil
}

func (m *AllRequest) GetUpdate() []byte {
	if m != nil {
		return m.Update
	}
	return nil
}

func (m *AllRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type BatchRequest struct {
	Batchrequest         []*AllRequest `protobuf:"bytes,1,rep,name=batchrequest,proto3" json:"batchrequest,omitempty"`
	Meta                 *Meta         `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BatchRequest) Reset()         { *m = BatchRequest{} }
func (m *BatchRequest) String() string { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()    {}
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *BatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchRequest.Unmarshal(m, b)
}
func (m *BatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchRequest.Marshal(b, m, deterministic)
}
func (m *BatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchRequest.Merge(m, src)
}
func (m *BatchRequest) XXX_Size() int {
	return xxx_messageInfo_BatchRequest.Size(m)
}
func (m *BatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BatchRequest proto.InternalMessageInfo

func (m *BatchRequest) GetBatchrequest() []*AllRequest {
	if m != nil {
		return m.Batchrequest
	}
	return nil
}

func (m *BatchRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type FaaSRequest struct {
	Params               []byte   `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Timeout              int64    `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Engine               string   `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	Function             string   `protobuf:"bytes,4,opt,name=function,proto3" json:"function,omitempty"`
	Token                string   `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaaSRequest) Reset()         { *m = FaaSRequest{} }
func (m *FaaSRequest) String() string { return proto.CompactTextString(m) }
func (*FaaSRequest) ProtoMessage()    {}
func (*FaaSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *FaaSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaaSRequest.Unmarshal(m, b)
}
func (m *FaaSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaaSRequest.Marshal(b, m, deterministic)
}
func (m *FaaSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaaSRequest.Merge(m, src)
}
func (m *FaaSRequest) XXX_Size() int {
	return xxx_messageInfo_FaaSRequest.Size(m)
}
func (m *FaaSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FaaSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FaaSRequest proto.InternalMessageInfo

func (m *FaaSRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *FaaSRequest) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *FaaSRequest) GetEngine() string {
	if m != nil {
		return m.Engine
	}
	return ""
}

func (m *FaaSRequest) GetFunction() string {
	if m != nil {
		return m.Function
	}
	return ""
}

func (m *FaaSRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "client.CreateRequest")
	proto.RegisterType((*ReadRequest)(nil), "client.ReadRequest")
	proto.RegisterType((*ReadOptions)(nil), "client.ReadOptions")
	proto.RegisterMapType((map[string]int32)(nil), "client.ReadOptions.SelectEntry")
	proto.RegisterMapType((map[string]int32)(nil), "client.ReadOptions.SortEntry")
	proto.RegisterType((*UpdateRequest)(nil), "client.UpdateRequest")
	proto.RegisterType((*DeleteRequest)(nil), "client.DeleteRequest")
	proto.RegisterType((*AggregateRequest)(nil), "client.AggregateRequest")
	proto.RegisterType((*Response)(nil), "client.Response")
	proto.RegisterType((*Meta)(nil), "client.Meta")
	proto.RegisterType((*AllRequest)(nil), "client.AllRequest")
	proto.RegisterType((*BatchRequest)(nil), "client.BatchRequest")
	proto.RegisterType((*FaaSRequest)(nil), "client.FaaSRequest")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x7d, 0x4e, 0x1c, 0xb7, 0xbe, 0x49, 0xa5, 0x6a, 0x5e, 0x5f, 0x65, 0x45, 0xef, 0xe9, 0x45,
	0x5e, 0x65, 0x43, 0x50, 0x5b, 0x89, 0x52, 0x76, 0xa5, 0xc0, 0x0e, 0x81, 0xa6, 0xb0, 0x67, 0xea,
	0xdc, 0xa6, 0x26, 0x8e, 0xc7, 0x8c, 0xc7, 0x95, 0x2a, 0x7e, 0x01, 0x3b, 0x96, 0xfc, 0x0f, 0x7e,
	0x1e, 0x1b, 0x34, 0x5f, 0xfe, 0xa8, 0x92, 0x96, 0xaa, 0xbb, 0x39, 0xf1, 0x9c, 0x7b, 0xef, 0x9c,
	0x73, 0xef, 0x0d, 0x8c, 0x4a, 0x14, 0xd7, 0x28, 0x66, 0x85, 0xe0, 0x92, 0x93, 0x20, 0xc9, 0x52,
	0xcc, 0x65, 0xbc, 0x84, 0x9d, 0x33, 0x81, 0x4c, 0x22, 0xc5, 0x2f, 0x15, 0x96, 0x92, 0x8c, 0x61,
	0x7b, 0xce, 0x93, 0x6a, 0x85, 0xb9, 0x8c, 0xbc, 0x89, 0x37, 0x1d, 0xd1, 0x1a, 0x93, 0x7f, 0x21,
	0xe4, 0x05, 0x0a, 0x26, 0x53, 0x9e, 0x47, 0xbd, 0x89, 0x37, 0x0d, 0x69, 0xf3, 0x03, 0x99, 0x80,
	0xbf, 0x42, 0xc9, 0xa2, 0xfe, 0xc4, 0x9b, 0x0e, 0x0f, 0x47, 0x33, 0x93, 0x61, 0xf6, 0x16, 0x25,
	0xa3, 0xfa, 0x4b, 0xfc, 0xdd, 0x83, 0x21, 0x45, 0x36, 0x77, 0xb9, 0x08, 0xf8, 0x97, 0x69, 0x3e,
	0xb7, 0x79, 0xf4, 0xf9, 0x9e, 0x1c, 0x4f, 0x60, 0x8b, 0x17, 0xea, 0x54, 0xda, 0x34, 0x7f, 0xbb,
	0x34, 0x2a, 0xee, 0x3b, 0xf3, 0x89, 0xba, 0x3b, 0x75, 0x49, 0xfe, 0xc6, 0x92, 0x7e, 0xf6, 0x4c,
	0x49, 0x96, 0x4a, 0x8e, 0x21, 0x28, 0x31, 0xc3, 0x44, 0x3d, 0xbe, 0x3f, 0x1d, 0x1e, 0xfe, 0xbf,
	0x26, 0xfe, 0xec, 0x5c, 0xdf, 0x78, 0x9d, 0x4b, 0x71, 0x43, 0xed, 0x75, 0x72, 0x00, 0x7e, 0xc9,
	0x85, 0x8c, 0x7a, 0x9a, 0xf6, 0xdf, 0x5a, 0x1a, 0x17, 0x96, 0xa4, 0xaf, 0xaa, 0xe7, 0x97, 0xcb,
	0xb4, 0xd0, 0x2f, 0xe9, 0x53, 0x7d, 0x26, 0x7b, 0x30, 0xc8, 0xd2, 0x55, 0x2a, 0x75, 0xc9, 0x7d,
	0x6a, 0x80, 0x36, 0x25, 0x2d, 0x65, 0x9a, 0x27, 0x32, 0x1a, 0x68, 0x4d, 0x6a, 0x3c, 0x3e, 0x81,
	0x61, 0xab, 0x1e, 0xb2, 0x0b, 0xfd, 0x25, 0xde, 0x68, 0x49, 0x43, 0xaa, 0x8e, 0x2a, 0xe4, 0x35,
	0xcb, 0x2a, 0xd4, 0x6a, 0x0e, 0xa8, 0x01, 0x2f, 0x7a, 0xcf, 0xbd, 0xf1, 0x31, 0x84, 0x75, 0x4d,
	0x0f, 0x21, 0xc6, 0x5f, 0x61, 0xe7, 0x63, 0x31, 0x6f, 0x75, 0xcd, 0xc3, 0x9d, 0xdc, 0x87, 0xa0,
	0xd2, 0x21, 0xf4, 0xf3, 0x47, 0xd4, 0xa2, 0x3f, 0xb0, 0x2c, 0x81, 0x9d, 0x57, 0x98, 0xe1, 0x63,
	0x92, 0xdf, 0xdf, 0xaa, 0x39, 0xec, 0x9e, 0x2e, 0x16, 0x02, 0x17, 0xdd, 0xd1, 0x28, 0xd2, 0x02,
	0xb3, 0x34, 0x47, 0x37, 0x1a, 0x0e, 0x3f, 0x3a, 0xdf, 0x7b, 0xd8, 0xa6, 0x58, 0x16, 0x3c, 0x2f,
	0x51, 0x49, 0x53, 0x4a, 0x26, 0xab, 0x52, 0x67, 0x19, 0x50, 0x8b, 0x94, 0x1f, 0x28, 0x04, 0x17,
	0x36, 0xbe, 0x01, 0xea, 0xb6, 0xc0, 0xb2, 0xca, 0xa4, 0x13, 0xd2, 0xa0, 0xf8, 0x13, 0xf8, 0x2a,
	0x3e, 0x89, 0x60, 0xab, 0x10, 0xfc, 0xb3, 0x69, 0x69, 0xc5, 0x73, 0x50, 0x31, 0xe7, 0x17, 0x1f,
	0x6e, 0x0a, 0xb4, 0x01, 0x2d, 0x52, 0x9d, 0x90, 0xf0, 0x4c, 0x87, 0x0b, 0xa9, 0x3a, 0xaa, 0xcc,
	0x92, 0x2f, 0x31, 0xd7, 0xae, 0x84, 0xd4, 0x80, 0xf8, 0x87, 0x07, 0x70, 0x9a, 0x65, 0x4e, 0x1e,
	0x4b, 0xf3, 0x1a, 0x5a, 0x7b, 0x97, 0xf4, 0xee, 0xda, 0x25, 0xfd, 0xdb, 0x82, 0x39, 0x4b, 0xfd,
	0x96, 0xa5, 0x4d, 0xc7, 0x0c, 0x3a, 0x1d, 0x43, 0xc0, 0x97, 0xea, 0x11, 0x81, 0x0e, 0xa2, 0xcf,
	0xf1, 0x15, 0x8c, 0x5e, 0x32, 0x99, 0x5c, 0xb9, 0xda, 0x9e, 0xc1, 0xe8, 0x42, 0x61, 0x61, 0xb0,
	0x1d, 0x6e, 0xe2, 0x8c, 0x68, 0x5e, 0x41, 0x3b, 0xf7, 0x6a, 0xe3, 0x7a, 0x1b, 0x8d, 0xfb, 0xe6,
	0xc1, 0xf0, 0x0d, 0x63, 0xe7, 0x2e, 0xd3, 0x3e, 0x04, 0x05, 0x13, 0x6c, 0x55, 0xda, 0x16, 0xb1,
	0x48, 0xd9, 0x20, 0xd3, 0x15, 0xf2, 0xca, 0x48, 0xd1, 0xa7, 0x0e, 0x2a, 0x06, 0xe6, 0x0b, 0xd5,
	0x54, 0x46, 0x06, 0x8b, 0x94, 0x7a, 0x97, 0x55, 0x9e, 0x68, 0x81, 0x8c, 0xee, 0x35, 0x6e, 0x0c,
	0x19, 0xb4, 0x0c, 0x39, 0xfc, 0xd5, 0x03, 0x38, 0x2f, 0x58, 0x82, 0x67, 0x19, 0xaf, 0xe6, 0xe4,
	0x08, 0x02, 0xb3, 0xdb, 0xc9, 0x3f, 0xae, 0xf0, 0xce, 0xae, 0x1f, 0xef, 0x36, 0x5b, 0xca, 0xb4,
	0x5e, 0xfc, 0x17, 0x79, 0x0a, 0xbe, 0xda, 0x59, 0xa4, 0xb3, 0x58, 0xef, 0x22, 0x1c, 0x41, 0x60,
	0x76, 0x41, 0x93, 0xa5, 0xb3, 0x1b, 0x36, 0x91, 0xcc, 0x0c, 0x37, 0xa4, 0xce, 0x4c, 0xaf, 0x25,
	0x9d, 0x40, 0x58, 0xcf, 0x24, 0x89, 0x6a, 0xef, 0x6e, 0x8d, 0xe9, 0x5a, 0xea, 0x01, 0x0c, 0x74,
	0x3f, 0x90, 0x3d, 0xf7, 0xb1, 0xdd, 0x1e, 0x9b, 0x84, 0x38, 0x63, 0x59, 0xd6, 0x08, 0xd1, 0x72,
	0x79, 0x1d, 0xe1, 0x22, 0xd0, 0xff, 0xac, 0x47, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xf3,
	0x45, 0xf3, 0x69, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpaceCloudClient is the client API for SpaceCloud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpaceCloudClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*Response, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*Response, error)
	Call(ctx context.Context, in *FaaSRequest, opts ...grpc.CallOption) (*Response, error)
}

type spaceCloudClient struct {
	cc *grpc.ClientConn
}

func NewSpaceCloudClient(cc *grpc.ClientConn) SpaceCloudClient {
	return &spaceCloudClient{cc}
}

func (c *spaceCloudClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Aggregate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Batch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spaceCloudClient) Call(ctx context.Context, in *FaaSRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/client.SpaceCloud/Call", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpaceCloudServer is the server API for SpaceCloud service.
type SpaceCloudServer interface {
	Create(context.Context, *CreateRequest) (*Response, error)
	Read(context.Context, *ReadRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*Response, error)
	Delete(context.Context, *DeleteRequest) (*Response, error)
	Aggregate(context.Context, *AggregateRequest) (*Response, error)
	Batch(context.Context, *BatchRequest) (*Response, error)
	Call(context.Context, *FaaSRequest) (*Response, error)
}

func RegisterSpaceCloudServer(s *grpc.Server, srv SpaceCloudServer) {
	s.RegisterService(&_SpaceCloud_serviceDesc, srv)
}

func _SpaceCloud_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Aggregate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Aggregate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Aggregate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Aggregate(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Batch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Batch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Batch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpaceCloud_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaaSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpaceCloudServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.SpaceCloud/Call",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpaceCloudServer).Call(ctx, req.(*FaaSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpaceCloud_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.SpaceCloud",
	HandlerType: (*SpaceCloudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SpaceCloud_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _SpaceCloud_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SpaceCloud_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SpaceCloud_Delete_Handler,
		},
		{
			MethodName: "Aggregate",
			Handler:    _SpaceCloud_Aggregate_Handler,
		},
		{
			MethodName: "Batch",
			Handler:    _SpaceCloud_Batch_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _SpaceCloud_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
